### ISSUE TITLE
the pretrained model was load many times.

### ISSUE THREAD

**Issue by wang-tf** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#13]
Is there any reason load model weight for every subject_id loop ? 

https://github.com/Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning/blob/438bf3ff4aed9b1283effc85a50a769e790d5444/retrain_rppg_personalization.py#L126

**Comment by Fabian-Sc85** [comment]
Hi, yes this is intentional. We are retraining the pretrained neural network for every subject in our rPPG dataset independently which requires us to reload the pretrained model (or rather its weights) for every subject. This way we could investigate whether using subject-specific data (20 % of each subject‘s data) improves the prediction error after fine tuning.

**Comment by wang-tf** [comment]
Thanks, I understand.
