### ISSUE TITLE
Why heartpy.process() is used for SBP DBP conversion from ABP?

### ISSUE THREAD

**Issue by gohjiayi** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#17]
Based off this code snippet below, it is understood that SBP and DBP is derived using the heartpy.process() function performing peak detection. However, looking at the documentation of the heartpy package, this function is meant for heart rate data and is not made for blood pressure data (see [here](https://python-heart-rate-analysis-toolkit.readthedocs.io/en/latest/quickstart.html)).

I would like to understand your rationale of using this specific function instead of other peak detection methods (e.g. scipy) for ABP data.

https://github.com/Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning/blob/438bf3ff4aed9b1283effc85a50a769e790d5444/download_mimic_iii_records.py#L76-L84

**Comment by Fabian-Sc85** [comment]
Hi, the heartpy package can be used to process PPG signals as demonstrated [here](https://github.com/paulvangentcom/heartrate_analysis_python/blob/master/examples/1_regular_PPG/Analysing_a_PPG_signal.ipynb). Since the ABP signals has a very similar shape it is possible to use this tooblox the analyse invasive blood pressure data. The peak detection functions provided by scipy would have produced many spurious peaks that I was not interested in (e.g. the diastolic peak) as these are general purpose peak detection methods intended to detect any peak in the signals.
