### ISSUE TITLE
rPPG Trained Deeplearning model...

### ISSUE THREAD

**Issue by bioconnect** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#8]
Do you have any plans to publish a model trained up to rPPG???

Thanks so much for the info on models trained on non-mixed data!

**Comment by Fabian-Sc85** [comment]
Hi, do you mean models that were trained solely on rPPG signals? I am afraid we don't have enough data to train these huge models from scratch. Otherwise, the pretrained models can be fine-tuned for rPPG-based BP prediction using the script `retrain_rppg_personalization.py`. The models that were pretrained on PPG signals (from the MIMIC-III database) can be downloaded from [Zenodo](https://zenodo.org/record/5590603). Hope this helps.
